<a href="https://colab.research.google.com/github/iqbal-prayogi/preprocessing/blob/main/prepocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df = pd.read_csv("listings.csv")

print(df.shape)
df.info()
display(df.head())

(500, 90)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 90 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            500 non-null    int64
 1   listing_url                                   500 non-null    object
 2   scrape_id                                     500 non-null    int64
 3   last_scraped                                  500 non-null    object
 4   source                                        35 non-null     object
 5   name                                          500 non-null    object
 6   description                                   497 non-null    object
 7   neighborhood_overview                         0 non-null      float64
 8   picture_url                                   500 non-null    object
 9   host_id                                       500 non-null    int64
 10  host_url                                      500 non-null    object
 11  host_profile_id                               500 non-null    int64
 12  host_profile_url                              500 non-null    object
 13  host_name                                     500 non-null    object
 14  host_since                                    0 non-null      float64
 15  hosts_time_as_user_years                      500 non-null    int64
 16  hosts_time_as_user_months                     500 non-null    int64
 17  hosts_time_as_host_years                      500 non-null    int64
 18  hosts_time_as_host_months                     500 non-null    int64
 19  host_location                                 357 non-null    object
 20  host_about                                    275 non-null    object
 21  host_response_time                            0 non-null      float64
 22  host_response_rate                            0 non-null      float64
 23  host_acceptance_rate                          0 non-null      float64
 24  host_is_superhost                             500 non-null    object
 25  host_thumbnail_url                            0 non-null      float64
 26  host_picture_url                              500 non-null    object
 27  host_neighbourhood                            0 non-null      float64
 28  host_listings_count                           500 non-null    int64
 29  host_total_listings_count                     0 non-null      float64
 30  host_verifications                            0 non-null      float64
 31  host_has_profile_pic                          500 non-null    object
 32  host_identity_verified                        500 non-null    object
 33  neighbourhood                                 0 non-null      float64
 34  neighbourhood_cleansed                        500 non-null    object
 35  neighbourhood_group_cleansed                  0 non-null      float64
 36  latitude                                      500 non-null    float64
 37  longitude                                     500 non-null    float64
 38  property_type                                 500 non-null    object
 39  room_type                                     500 non-null    object
 40  accommodates                                  500 non-null    int64
 41  bathrooms                                     0 non-null      float64
 42  bathrooms_text                                500 non-null    object
 43  bedrooms                                      500 non-null    int64
 44  beds                                          493 non-null    float64
 45  amenities                                     500 non-null    object
 46  price                                         467 non-null    object
 47  price_quote_checkin_date                      478 non-null    object
 48  price_quote_checkout_date                     478 non-null    object
 49  price_quote_total_price                       467 non-null    float64
 50  price_quote_price_per_night                   467 non-null    float64
 51  price_quote_raw                               478 non-null    object
 52  minimum_nights                                499 non-null    float64
 53  maximum_nights                                499 non-null    float64
 54  minimum_minimum_nights                        499 non-null    float64
 55  maximum_minimum_nights                        499 non-null    float64
 56  minimum_maximum_nights                        499 non-null    float64
 57  maximum_maximum_nights                        499 non-null    float64
 58  minimum_nights_avg_ntm                        500 non-null    float64
 59  maximum_nights_avg_ntm                        500 non-null    float64
 60  calendar_updated                              0 non-null      float64
 61  has_availability                              497 non-null    object
 62  availability_30                               500 non-null    int64
 63  availability_60                               500 non-null    int64
 64  availability_90                               500 non-null    int64
 65  availability_365                              500 non-null    int64
 66  calendar_last_scraped                         500 non-null    object
 67  number_of_reviews                             500 non-null    int64
 68  number_of_reviews_ltm                         500 non-null    int64
 69  number_of_reviews_l30d                        500 non-null    int64
 70  availability_eoy                              500 non-null    int64
 71  number_of_reviews_ly                          500 non-null    int64
 72  estimated_occupancy_l365d                     500 non-null    int64
 73  estimated_revenue_l365d                       467 non-null    float64
 74  first_review                                  449 non-null    object
 75  last_review                                   449 non-null    object
 76  review_scores_rating                          449 non-null    float64
 77  review_scores_accuracy                        449 non-null    float64
 78  review_scores_cleanliness                     449 non-null    float64
 79  review_scores_checkin                         449 non-null    float64
 80  review_scores_communication                   449 non-null    float64
 81  review_scores_location                        449 non-null    float64
 82  review_scores_value                           449 non-null    float64
 83  license                                       0 non-null      float64
 84  instant_bookable                              0 non-null      float64
 85  calculated_host_listings_count                500 non-null    int64
 86  calculated_host_listings_count_entire_homes   500 non-null    int64
 87  calculated_host_listings_count_private_rooms  500 non-null    int64
 88  calculated_host_listings_count_shared_rooms   500 non-null    int64
 89  reviews_per_month                             449 non-null    float64
dtypes: float64(37), int64(25), object(28)
memory usage: 351.7+ KB

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2992450,https://www.airbnb.com/rooms/2992450,20260914164327,2026-09-16,NaN,Luxury 2 bedroom apartment,The apartment is located in a quiet neighborho...,NaN,https://a0.muscache.com/pictures/44627226/0e72...,4621559,...,4.56,3.22,3.67,NaN,NaN,1,1,0,0,0.06
1,3820211,https://www.airbnb.com/rooms/3820211,20260914164327,2026-09-16,NaN,Restored Precinct in Center Sq. w/Parking,Step into the charming and comfy 1BR/1BA apart...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,19648678,...,4.81,4.81,4.78,NaN,NaN,7,7,0,0,2.17
2,6623339,https://www.airbnb.com/rooms/6623339,20260914164327,2026-09-16,NaN,Center Sq. Loft in Converted Precinct w/ Parking,Step into the charming and comfy 1BR/1BA apart...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,19648678,...,4.72,4.79,4.73,NaN,NaN,7,7,0,0,2.50
3,9501054,https://www.airbnb.com/rooms/9501054,20260914164327,2026-09-16,NaN,Spacious suite with full bath by Capital Center,Great location within walking distance to the ...,NaN,https://a0.muscache.com/pictures/45153167-d704...,29288920,...,4.87,4.77,4.68,NaN,NaN,1,0,1,0,3.70
4,10768745,https://www.airbnb.com/rooms/10768745,20260914164327,2026-09-16,NaN,Alb hospital area studio bath wifi. (Red),Spacious warm studio in 1840 house close to ho...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,5691268,...,4.89,4.93,4.91,NaN,NaN,2,0,2,0,7.28

In [ ]:
df.info()
display(df.describe().T)

missing = df.isnull().sum()
missing = pd.DataFrame({"jumlah": missing, "persen": (missing / len(df) * 100).round(2)})
display(missing[missing.jumlah > 0].sort_values("persen", ascending=False))
print("Duplikat:", df.duplicated().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 90 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            500 non-null    int64
 1   listing_url                                   500 non-null    object
 2   scrape_id                                     500 non-null    int64
 3   last_scraped                                  500 non-null    object
 4   source                                        35 non-null     object
 5   name                                          500 non-null    object
 6   description                                   497 non-null    object
 7   neighborhood_overview                         0 non-null      float64
 8   picture_url                                   500 non-null    object
 9   host_id                                       500 non-null    int64
 10  host_url                                      500 non-null    object
 11  host_profile_id                               500 non-null    int64
 12  host_profile_url                              500 non-null    object
 13  host_name                                     500 non-null    object
 14  host_since                                    0 non-null      float64
 15  hosts_time_as_user_years                      500 non-null    int64
 16  hosts_time_as_user_months                     500 non-null    int64
 17  hosts_time_as_host_years                      500 non-null    int64
 18  hosts_time_as_host_months                     500 non-null    int64
 19  host_location                                 357 non-null    object
 20  host_about                                    275 non-null    object
 21  host_response_time                            0 non-null      float64
 22  host_response_rate                            0 non-null      float64
 23  host_acceptance_rate                          0 non-null      float64
 24  host_is_superhost                             500 non-null    object
 25  host_thumbnail_url                            0 non-null      float64
 26  host_picture_url                              500 non-null    object
 27  host_neighbourhood                            0 non-null      float64
 28  host_listings_count                           500 non-null    int64
 29  host_total_listings_count                     0 non-null      float64
 30  host_verifications                            0 non-null      float64
 31  host_has_profile_pic                          500 non-null    object
 32  host_identity_verified                        500 non-null    object
 33  neighbourhood                                 0 non-null      float64
 34  neighbourhood_cleansed                        500 non-null    object
 35  neighbourhood_group_cleansed                  0 non-null      float64
 36  latitude                                      500 non-null    float64
 37  longitude                                     500 non-null    float64
 38  property_type                                 500 non-null    object
 39  room_type                                     500 non-null    object
 40  accommodates                                  500 non-null    int64
 41  bathrooms                                     0 non-null      float64
 42  bathrooms_text                                500 non-null    object
 43  bedrooms                                      500 non-null    int64
 44  beds                                          493 non-null    float64
 45  amenities                                     500 non-null    object
 46  price                                         467 non-null    object
 47  price_quote_checkin_date                      478 non-null    object
 48  price_quote_checkout_date                     478 non-null    object
 49  price_quote_total_price                       467 non-null    float64
 50  price_quote_price_per_night                   467 non-null    float64
 51  price_quote_raw                               478 non-null    object
 52  minimum_nights                                499 non-null    float64
 53  maximum_nights                                499 non-null    float64
 54  minimum_minimum_nights                        499 non-null    float64
 55  maximum_minimum_nights                        499 non-null    float64
 56  minimum_maximum_nights                        499 non-null    float64
 57  maximum_maximum_nights                        499 non-null    float64
 58  minimum_nights_avg_ntm                        500 non-null    float64
 59  maximum_nights_avg_ntm                        500 non-null    float64
 60  calendar_updated                              0 non-null      float64
 61  has_availability                              497 non-null    object
 62  availability_30                               500 non-null    int64
 63  availability_60                               500 non-null    int64
 64  availability_90                               500 non-null    int64
 65  availability_365                              500 non-null    int64
 66  calendar_last_scraped                         500 non-null    object
 67  number_of_reviews                             500 non-null    int64
 68  number_of_reviews_ltm                         500 non-null    int64
 69  number_of_reviews_l30d                        500 non-null    int64
 70  availability_eoy                              500 non-null    int64
 71  number_of_reviews_ly                          500 non-null    int64
 72  estimated_occupancy_l365d                     500 non-null    int64
 73  estimated_revenue_l365d                       467 non-null    float64
 74  first_review                                  449 non-null    object
 75  last_review                                   449 non-null    object
 76  review_scores_rating                          449 non-null    float64
 77  review_scores_accuracy                        449 non-null    float64
 78  review_scores_cleanliness                     449 non-null    float64
 79  review_scores_checkin                         449 non-null    float64
 80  review_scores_communication                   449 non-null    float64
 81  review_scores_location                        449 non-null    float64
 82  review_scores_value                           449 non-null    float64
 83  license                                       0 non-null      float64
 84  instant_bookable                              0 non-null      float64
 85  calculated_host_listings_count                500 non-null    int64
 86  calculated_host_listings_count_entire_homes   500 non-null    int64
 87  calculated_host_listings_count_private_rooms  500 non-null    int64
 88  calculated_host_listings_count_shared_rooms   500 non-null    int64
 89  reviews_per_month                             449 non-null    float64
dtypes: float64(37), int64(25), object(28)
memory usage: 351.7+ KB

,count,mean,std,min,25%,50%,75%,max
id,500.0,9.883705e+17,5.942214e+17,2.992450e+06,7.042966e+17,1.120956e+18,1.477201e+18,1.773591e+18
scrape_id,500.0,2.026091e+13,1.133947e-01,2.026091e+13,2.026091e+13,2.026091e+13,2.026091e+13,2.026091e+13
neighborhood_overview,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
host_id,500.0,2.412574e+16,2.027301e+17,6.490680e+05,5.143576e+07,2.117414e+08,4.667901e+08,1.767798e+18
host_profile_id,500.0,1.480443e+18,4.985197e+16,1.462518e+18,1.463574e+18,1.468352e+18,1.470110e+18,1.767798e+18
...,...,...,...,...,...,...,...,...
calculated_host_listings_count,500.0,7.420000e+00,7.911307e+00,1.000000e+00,2.000000e+00,4.000000e+00,1.100000e+01,3.100000e+01
calculated_host_listings_count_entire_homes,500.0,5.464000e+00,8.083030e+00,0.000000e+00,1.000000e+00,2.000000e+00,7.250000e+00,3.100000e+01
calculated_host_listings_count_private_rooms,500.0,1.944000e+00,3.866104e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00,1.500000e+01
calculated_host_listings_count_shared_rooms,500.0,1.200000e-02,1.089943e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
reviews_per_month,449.0,1.753519e+00,1.878271e+00,4.000000e-02,3.500000e-01,1.150000e+00,2.510000e+00,1.054000e+01

                              jumlah  persen
host_since                       500   100.0
neighborhood_overview            500   100.0
host_response_time               500   100.0
host_response_rate               500   100.0
host_neighbourhood               500   100.0
host_total_listings_count        500   100.0
host_thumbnail_url               500   100.0
host_acceptance_rate             500   100.0
bathrooms                        500   100.0
neighbourhood_group_cleansed     500   100.0
neighbourhood                    500   100.0
host_verifications               500   100.0
instant_bookable                 500   100.0
license                          500   100.0
calendar_updated                 500   100.0
source                           465    93.0
host_about                       225    45.0
host_location                    143    28.6
reviews_per_month                 51    10.2
review_scores_checkin             51    10.2
first_review                      51    10.2
last_review                       51    10.2
review_scores_cleanliness         51    10.2
review_scores_accuracy            51    10.2
review_scores_rating              51    10.2
review_scores_value               51    10.2
review_scores_communication       51    10.2
review_scores_location            51    10.2
estimated_revenue_l365d           33     6.6
price_quote_price_per_night       33     6.6
price_quote_total_price           33     6.6
price                             33     6.6
price_quote_checkout_date         22     4.4
price_quote_checkin_date          22     4.4
price_quote_raw                   22     4.4
beds                               7     1.4
description                        3     0.6
has_availability                   3     0.6
minimum_maximum_nights             1     0.2
maximum_nights                     1     0.2
minimum_nights                     1     0.2
maximum_minimum_nights             1     0.2
minimum_minimum_nights             1     0.2
maximum_maximum_nights             1     0.2

Duplikat: 0

In [ ]:
import pandas as pd
import numpy as np

# Membuat salinan dari dataframe asli agar data original tetap aman
df_clean = df.copy()

# 1. Mengisi nilai kosong pada kolom numerik dengan median
numerik_cols = df_clean.select_dtypes(include=[np.number]).columns
for col in numerik_cols:
    if df_clean[col].isnull().any():
        if df_clean[col].isnull().all():
            df_clean[col] = df_clean[col].fillna(0)
        else:
            median_val = df_clean[col].median()
            df_clean[col] = df_clean[col].fillna(median_val)

# 2. Mengisi nilai kosong pada kolom objek/kategori dengan 'Unknown'
object_cols = df_clean.select_dtypes(include=['object']).columns
for col in object_cols:
    if df_clean[col].isnull().any():
        df_clean[col] = df_clean[col].fillna('Unknown')

# Memverifikasi hasil preprocessing
sisa_null = df_clean.isnull().sum().sum()
print(f"Jumlah kolom awal: {df.shape[1]} -> Jumlah kolom setelah diproses: {df_clean.shape[1]}")
print(f"Jumlah total nilai kosong (null) yang tersisa: {sisa_null}")
display(df_clean.head())

Jumlah kolom awal: 90 -> Jumlah kolom setelah diproses: 90
Jumlah total nilai kosong (null) yang tersisa: 0

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2992450,https://www.airbnb.com/rooms/2992450,20260914164327,2026-09-16,Unknown,Luxury 2 bedroom apartment,The apartment is located in a quiet neighborho...,0.0,https://a0.muscache.com/pictures/44627226/0e72...,4621559,...,4.56,3.22,3.67,0.0,0.0,1,1,0,0,0.06
1,3820211,https://www.airbnb.com/rooms/3820211,20260914164327,2026-09-16,Unknown,Restored Precinct in Center Sq. w/Parking,Step into the charming and comfy 1BR/1BA apart...,0.0,https://a0.muscache.com/pictures/hosting/Hosti...,19648678,...,4.81,4.81,4.78,0.0,0.0,7,7,0,0,2.17
2,6623339,https://www.airbnb.com/rooms/6623339,20260914164327,2026-09-16,Unknown,Center Sq. Loft in Converted Precinct w/ Parking,Step into the charming and comfy 1BR/1BA apart...,0.0,https://a0.muscache.com/pictures/hosting/Hosti...,19648678,...,4.72,4.79,4.73,0.0,0.0,7,7,0,0,2.50
3,9501054,https://www.airbnb.com/rooms/9501054,20260914164327,2026-09-16,Unknown,Spacious suite with full bath by Capital Center,Great location within walking distance to the ...,0.0,https://a0.muscache.com/pictures/45153167-d704...,29288920,...,4.87,4.77,4.68,0.0,0.0,1,0,1,0,3.70
4,10768745,https://www.airbnb.com/rooms/10768745,20260914164327,2026-09-16,Unknown,Alb hospital area studio bath wifi. (Red),Spacious warm studio in 1840 house close to ho...,0.0,https://a0.muscache.com/pictures/hosting/Hosti...,5691268,...,4.89,4.93,4.91,0.0,0.0,2,0,2,0,7.28

In [ ]:
# 1. Memeriksa sisa nilai kosong (null) di setiap kolom untuk memastikan tidak ada yang terlewat
missing_after = df_clean.isnull().sum()
missing_after_df = pd.DataFrame({"jumlah_null": missing_after, "persen_null": (missing_after / len(df_clean) * 100).round(2)})

print("--- Informasi Dataset Setelah Preprocessing ---")
print(f"Ukuran Baris & Kolom: {df_clean.shape}")
print(f"Jumlah Duplikat: {df_clean.duplicated().sum()}")
print("\n--- Kolom yang Sebelumnya Memiliki Null (Memastikan sudah bersih) ---")

# Menampilkan kolom-kolom yang sebelumnya memiliki null pada 'df' asli
kolom_null_sebelumnya = df.columns[df.isnull().sum() > 0]
display(missing_after_df.loc[kolom_null_sebelumnya].sort_values("jumlah_null", ascending=False).head(15))

print("\n--- Contoh Data Hasil Imputasi (5 baris acak) ---")
display(df_clean[kolom_null_sebelumnya].sample(5, random_state=42))

--- Informasi Dataset Setelah Preprocessing ---
Ukuran Baris & Kolom: (500, 90)
Jumlah Duplikat: 0

--- Kolom yang Sebelumnya Memiliki Null (Memastikan sudah bersih) ---

                              jumlah_null  persen_null
source                                  0          0.0
description                             0          0.0
neighborhood_overview                   0          0.0
host_since                              0          0.0
host_location                           0          0.0
host_about                              0          0.0
host_response_time                      0          0.0
host_response_rate                      0          0.0
host_acceptance_rate                    0          0.0
host_thumbnail_url                      0          0.0
host_neighbourhood                      0          0.0
host_total_listings_count               0          0.0
host_verifications                      0          0.0
neighbourhood                           0          0.0
neighbourhood_group_cleansed            0          0.0

--- Contoh Data Hasil Imputasi (5 baris acak) ---

,source,description,neighborhood_overview,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_thumbnail_url,...,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,reviews_per_month
361,Unknown,"Welcome to The Dove’s Nest, a cozy and quiet s...",0.0,0.0,"New York, United States","Hey, I’m Roland! I work full-time as an electr...",0.0,0.0,0.0,0.0,...,4.87,4.81,4.77,4.77,4.97,4.87,4.84,0.0,0.0,2.17
73,Unknown,800 sqft rustic style master suite room in the...,0.0,0.0,"Albany, NY",Airbnb has transformed every part of my life f...,0.0,0.0,0.0,0.0,...,4.96,4.97,4.98,4.96,4.98,4.97,4.98,0.0,0.0,3.28
374,Unknown,Welcome to your home away from home in the hea...,0.0,0.0,"Albany, NY",Hello Everyone. \nMy name is Nori; I am a land...,0.0,0.0,0.0,0.0,...,4.94,4.92,4.97,4.99,4.97,4.74,4.82,0.0,0.0,6.00
155,Unknown,Perfect location with exposed brick 1 bedroom ...,0.0,0.0,"New York, NY",Hello just a traveler who loves to enjoy other...,0.0,0.0,0.0,0.0,...,4.69,4.79,4.67,4.80,4.89,4.82,4.74,0.0,0.0,1.39
104,previous scrape,This charming townhouse is located in the hist...,0.0,0.0,"Albany, NY",Hello! I’ve been a resident of Albany my whole...,0.0,0.0,0.0,0.0,...,4.98,4.98,4.96,4.99,5.00,4.95,4.98,0.0,0.0,4.86